### ISSUE TITLE
solved cuda problem?

### ISSUE THREAD

**Issue by jjiikkkk** [devhasibulislam/autotrain-dreambooth#1]
this colab cannot be used for a few days

**Comment by devhasibulislam** [comment]
Why, is there any issue?

**Comment by devhasibulislam** [comment]
> this colab cannot be used for a few days

Why, is there any issue?

**Comment by jjiikkkk** [comment]
xformer cannot be used, although it is installed
then i use false
then always

 ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 273, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 419, in train
    text_encoder2 = text_encoder2.to(torch.float32)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2271, in to
    return super().to(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 4.81 MiB is free. Process 369424 has 14.74 G

**Comment by devhasibulislam** [comment]
> xformer cannot be used, although it is installed then i use false then always
> 
> ERROR Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper return func(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/**main**.py", line 273, in train trainer.train() File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 419, in train text_encoder2 = text_encoder2.to(torch.float32) File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2271, in to return super().to(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1160, in to return self._apply(convert) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply module._apply(fn) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply module._apply(fn) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply module._apply(fn) [Previous line repeated 3 more times] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 833, in _apply param_applied = fn(param) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1158, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 4.81 MiB is free. Process 369424 has 14.74 G

Well I'm also stuck with it, can you help me there?
